# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_redis_sync.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_redis_sync(object):
    def setupUi(self, Form_redis_sync):
        Form_redis_sync.setObjectName("Form_redis_sync")
        Form_redis_sync.resize(639, 456)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(Form_redis_sync)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_source = QtWidgets.QGroupBox(Form_redis_sync)
        self.groupBox_source.setObjectName("groupBox_source")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_source)
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_source)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_source_host = QtWidgets.QLineEdit(self.groupBox_source)
        self.lineEdit_source_host.setObjectName("lineEdit_source_host")
        self.horizontalLayout.addWidget(self.lineEdit_source_host)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_source)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_source_port = QtWidgets.QLineEdit(self.groupBox_source)
        self.lineEdit_source_port.setObjectName("lineEdit_source_port")
        self.horizontalLayout_2.addWidget(self.lineEdit_source_port)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_source)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_source_auth = QtWidgets.QLineEdit(self.groupBox_source)
        self.lineEdit_source_auth.setObjectName("lineEdit_source_auth")
        self.horizontalLayout_3.addWidget(self.lineEdit_source_auth)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_8.addWidget(self.groupBox_source)
        self.groupBox_source_2 = QtWidgets.QGroupBox(Form_redis_sync)
        self.groupBox_source_2.setObjectName("groupBox_source_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_source_2)
        self.verticalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_source_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_destination_host = QtWidgets.QLineEdit(self.groupBox_source_2)
        self.lineEdit_destination_host.setObjectName("lineEdit_destination_host")
        self.horizontalLayout_4.addWidget(self.lineEdit_destination_host)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox_source_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineEdit_destination_port = QtWidgets.QLineEdit(self.groupBox_source_2)
        self.lineEdit_destination_port.setObjectName("lineEdit_destination_port")
        self.horizontalLayout_5.addWidget(self.lineEdit_destination_port)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.groupBox_source_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.lineEdit_destination_auth = QtWidgets.QLineEdit(self.groupBox_source_2)
        self.lineEdit_destination_auth.setObjectName("lineEdit_destination_auth")
        self.horizontalLayout_6.addWidget(self.lineEdit_destination_auth)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout_8.addWidget(self.groupBox_source_2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_conn = QtWidgets.QPushButton(Form_redis_sync)
        self.pushButton_conn.setObjectName("pushButton_conn")
        self.verticalLayout_5.addWidget(self.pushButton_conn)
        self.pushButton_sync = QtWidgets.QPushButton(Form_redis_sync)
        self.pushButton_sync.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_sync.setObjectName("pushButton_sync")
        self.verticalLayout_5.addWidget(self.pushButton_sync)
        self.checkBox_isPipe = QtWidgets.QCheckBox(Form_redis_sync)
        self.checkBox_isPipe.setObjectName("checkBox_isPipe")
        self.verticalLayout_5.addWidget(self.checkBox_isPipe)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEdit_rdb_path = QtWidgets.QLineEdit(Form_redis_sync)
        self.lineEdit_rdb_path.setObjectName("lineEdit_rdb_path")
        self.horizontalLayout_7.addWidget(self.lineEdit_rdb_path)
        self.pushButton_open = QtWidgets.QPushButton(Form_redis_sync)
        self.pushButton_open.setObjectName("pushButton_open")
        self.horizontalLayout_7.addWidget(self.pushButton_open)
        self.checkBox_isrdb = QtWidgets.QCheckBox(Form_redis_sync)
        self.checkBox_isrdb.setObjectName("checkBox_isrdb")
        self.horizontalLayout_7.addWidget(self.checkBox_isrdb)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.textEdit = QtWidgets.QTextEdit(Form_redis_sync)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_6.addWidget(self.textEdit)

        self.retranslateUi(Form_redis_sync)
        QtCore.QMetaObject.connectSlotsByName(Form_redis_sync)

    def retranslateUi(self, Form_redis_sync):
        _translate = QtCore.QCoreApplication.translate
        Form_redis_sync.setWindowTitle(_translate("Form_redis_sync", "SYNC"))
        self.groupBox_source.setTitle(_translate("Form_redis_sync", "source"))
        self.label.setText(_translate("Form_redis_sync", "host"))
        self.lineEdit_source_host.setText(_translate("Form_redis_sync", "127.0.0.1"))
        self.label_2.setText(_translate("Form_redis_sync", "port"))
        self.lineEdit_source_port.setText(_translate("Form_redis_sync", "6379"))
        self.label_3.setText(_translate("Form_redis_sync", "auth"))
        self.groupBox_source_2.setTitle(_translate("Form_redis_sync", "destination"))
        self.label_4.setText(_translate("Form_redis_sync", "host"))
        self.lineEdit_destination_host.setText(_translate("Form_redis_sync", "127.0.0.1"))
        self.label_5.setText(_translate("Form_redis_sync", "port"))
        self.lineEdit_destination_port.setText(_translate("Form_redis_sync", "6379"))
        self.label_6.setText(_translate("Form_redis_sync", "auth"))
        self.pushButton_conn.setText(_translate("Form_redis_sync", "connection"))
        self.pushButton_sync.setText(_translate("Form_redis_sync", "sync"))
        self.checkBox_isPipe.setText(_translate("Form_redis_sync", "isPipe"))
        self.pushButton_open.setText(_translate("Form_redis_sync", "open"))
        self.checkBox_isrdb.setText(_translate("Form_redis_sync", "isFromRDB"))
